services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo17:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8067:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - /c/Users/Bashir/Documents/odoo practice/ODOO CUSTOM MODULE ON SERVER/odoo-custom-module-on-server/enterprise:/mnt/enterprise  # Mount enterprise addons
    environment:
      - ADDONS_PATH=/mnt/enterprise,/mnt/extra-addons
    command: odoo -d odoo_db2 -i base --db_user=odoo --db_password=odoo --db_host=db

volumes:
  odoo-web-data:
  odoo-db-data:
